In [5]:
import numpy as np
import random

In [6]:
adj = []
for i in range(4):
    adj.append(random.sample(range(100),4))

In [7]:
adj

[[44, 95, 76, 99], [48, 70, 59, 43], [34, 59, 83, 31], [68, 45, 9, 91]]

In [8]:
for i in range(len(adj)):
    for j in range(len(adj[i])):
        if i==j:
            adj[i][j] = 999

In [9]:
np.array(adj)

array([[999,  95,  76,  99],
       [ 48, 999,  59,  43],
       [ 34,  59, 999,  31],
       [ 68,  45,   9, 999]])

In [10]:
min(adj[0])

76

In [11]:
adj

[[999, 95, 76, 99], [48, 999, 59, 43], [34, 59, 999, 31], [68, 45, 9, 999]]

In [12]:
start = int(input())

0


In [13]:
visited = []
dist = 0
visited.append(start)
while list(set(visited)) != [i for i in range(len(adj))]:
    for i in range(len(adj)):
        adj[i][visited[-1]] = 999
    nxt = adj[visited[-1]].index(min(adj[visited[-1]]))
    dist += min(adj[visited[-1]])
    print(np.array(adj))
    print(nxt)
    visited.append(nxt)
    continue

[[999  95  76  99]
 [999 999  59  43]
 [999  59 999  31]
 [999  45   9 999]]
2
[[999  95 999  99]
 [999 999 999  43]
 [999  59 999  31]
 [999  45 999 999]]
3
[[999  95 999 999]
 [999 999 999 999]
 [999  59 999 999]
 [999  45 999 999]]
1


In [14]:
dist

152

In [15]:
visited

[0, 2, 3, 1]